// src/components/back-to-top.tsx
"use client";

import { useState, useEffect } from "react";
import { ArrowUp } from "lucide-react";

export function BackToTop() {
  const [showButton, setShowButton] = useState(false);

  useEffect(() => {
    const handleScroll = () => {
      setShowButton(window.scrollY > 100);
    };

    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  const scrollToTop = () => {
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  if (!showButton) return null;

  return (
    <div className="fixed bottom-6 right-6 z-50">
      <button
        onClick={scrollToTop}
        aria-label="回到顶部"
        className="size-12 shadow-lg hover:shadow-xl bg-white text-black dark:bg-black dark:text-white border-2 border-border rounded-full inline-flex items-center justify-center transition-all hover:scale-105"
      >
        <ArrowUp className="size-5" />
      </button>
    </div>
  );
}

// src/components/BackToTop.svelte
<script lang="ts">
	import { ArrowUp } from '@lucide/svelte';

	let visible = $state(false);

	$effect(() => {
		if (typeof window === 'undefined') return;
		const f = () => { visible = window.scrollY > 400; };
		window.addEventListener('scroll', f, { passive: true });
		return () => window.removeEventListener('scroll', f);
	});

	function top() {
		window.scrollTo({ top: 0, behavior: 'smooth' });
	}
</script>

<button
	onclick={top}
	aria-label="回到顶端"
	class="fixed bottom-6 right-6 z-50 flex size-10 cursor-pointer items-center justify-center rounded-full border bg-background text-foreground shadow-lg transition-all duration-500 hover:shadow-xl"
	class:opacity-100={visible}
	class:opacity-0={!visible}
	class:translate-y-0={visible}
	class:translate-y-4={!visible}
	class:pointer-events-auto={visible}
	class:pointer-events-none={!visible}
>
	<ArrowUp class="!size-[18px]" />
</button>
