// src/components/ImageLightbox.svelte
<script lang="ts">
	let src = $state('');
	let visible = $state(false);

	$effect(() => {
		if (typeof window === 'undefined') return;
		function handler(e: MouseEvent) {
			const target = e.target as HTMLElement;
			if (target.tagName === 'IMG' && target.closest('.prose')) {
				src = (target as HTMLImageElement).src;
				visible = true;
				document.body.style.overflow = 'hidden';
			}
		}
		document.addEventListener('click', handler);
		return () => document.removeEventListener('click', handler);
	});

	function close() {
		visible = false;
		document.body.style.overflow = '';
		src = '';
	}

	function onKeydown(e: KeyboardEvent) {
		if (e.key === 'Escape') close();
	}

	function onBackdrop(e: MouseEvent) {
		if (e.target === e.currentTarget) close();
	}
</script>

<svelte:window onkeydown={onKeydown} />

{#if visible}
	<div
		class="fixed inset-0 z-[100] flex items-center justify-center bg-black/85 p-4"
		role="dialog"
		aria-modal="true"
		onclick={onBackdrop}
	>
		<img
			src={src}
			alt=""
			class="max-h-[90vh] max-w-[90vw] rounded object-contain shadow-2xl"
		/>

		<button
			onclick={close}
			aria-label="关闭"
			class="absolute right-4 top-4 flex size-10 cursor-pointer items-center justify-center rounded-full bg-white/10 text-white/80 text-lg transition-colors hover:bg-white/20 hover:text-white"
		>
			✕
		</button>

		<div class="absolute inset-x-0 bottom-6 text-center text-xs text-white/50 pointer-events-none">
			点击背景或按 ESC 关闭
		</div>
	</div>
{/if}

// src/components/image-lightbox.tsx
"use client";

import { useState, useCallback } from "react";
import { X, ZoomIn } from "lucide-react";

interface ImageLightboxProps {
  src: string;
  alt: string;
  children?: React.ReactNode;
}

export function ImageLightbox({ src, alt }: ImageLightboxProps) {
  const [open, setOpen] = useState(false);

  const handleClose = useCallback(() => setOpen(false), []);

  return (
    <>
      {/* Clickable thumbnail */}
      <button
        type="button"
        onClick={() => setOpen(true)}
        className="relative group inline-block w-full cursor-zoom-in"
      >
        <img
          src={src}
          alt={alt}
          loading="lazy"
          className="w-full rounded-lg object-cover border border-border/50 transition-transform duration-200 group-hover:scale-[1.005]"
        />
        <div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-200 rounded-lg bg-black/10">
          <ZoomIn className="size-6 text-white drop-shadow-lg" />
        </div>
      </button>

      {/* Fullscreen overlay */}
      {open && (
        <div
          className="fixed inset-0 z-[100] flex items-center justify-center bg-black/80 backdrop-blur-sm"
          onClick={handleClose}
        >
          <button
            type="button"
            onClick={handleClose}
            className="absolute top-4 right-4 size-10 rounded-full bg-black/50 flex items-center justify-center text-white hover:bg-black/70 transition-colors z-10"
          >
            <X className="size-5" />
          </button>
          <img
            src={src}
            alt={alt}
            className="max-h-[92vh] max-w-[92vw] object-contain rounded-lg shadow-2xl"
            onClick={(e) => e.stopPropagation()}
          />
        </div>
      )}
    </>
  );
}
