// src/lib/components/NavBar.svelte
<script lang="ts">
  import { page } from '$app/stores';
  import { siteConfig } from '$lib/config/site';
  import ThemeToggle from './ThemeToggle.svelte';
  import { fly } from 'svelte/transition';

  let spinRaf = $state(0);
  let spinStart = $state(0);
  let spinOffset = $state(0);
  let spinDeg = $state(0);

  function startSpin() {
    cancelAnimationFrame(spinRaf);
    spinStart = performance.now();
    function tick(now: number) {
      const elapsed = now - spinStart;
      spinDeg = spinOffset + (Math.pow(2, elapsed / 3000) - 1) * 360;
      spinRaf = requestAnimationFrame(tick);
    }
    spinRaf = requestAnimationFrame(tick);
  }

  function stopSpin() {
    cancelAnimationFrame(spinRaf);
    spinOffset = spinDeg;
  }

  let crumbs = $derived.by(() => {
    const path = $page.url.pathname.replace(/\/$/, '') || '/';
    if (path === '/') return [];
    const parts = path.split('/').filter(Boolean);
    const displayNames: Record<string, string> = {
      posts: '文章',
      about: '关于',
      cover: '封面',
    };
    const result: { label: string; href: string }[] = [];
    let accumulated = '';
    for (let i = 0; i < parts.length; i++) {
      accumulated += '/' + parts[i];
      result.push({ label: displayNames[parts[i]] || parts[i], href: accumulated });
    }
    return result;
  });
</script>

<nav class="sticky top-0 z-40 w-full bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60 shadow-sm">
  <div class="relative flex h-10 items-center justify-between px-2">
    <div class="flex items-center gap-1 min-w-0">
      <a href="/" class="shrink-0 hover:opacity-80 transition-opacity" onmouseenter={startSpin} onmouseleave={stopSpin}>
        <img src={siteConfig.avatar} alt="Home" class="h-6 w-6 rounded-full" style="transform: rotate({spinDeg}deg);" referrerpolicy="no-referrer" />
      </a>
      {#each crumbs as crumb, i (crumb.href)}
        <div in:fly={{ x: -8, duration: 300 }} out:fly={{ x: 8, duration: 200 }} class="inline-flex items-center gap-1">
          <span class="text-muted-foreground/40 shrink-0">/</span>
          {#if i < crumbs.length - 1}
            <a href={crumb.href} class="text-xs text-muted-foreground hover:text-foreground truncate transition-colors shrink min-w-0">{crumb.label}</a>
          {:else}
            <span class="text-xs text-foreground font-medium truncate shrink min-w-0">{crumb.label}</span>
          {/if}
        </div>
      {/each}
    </div>
    <div class="flex items-center gap-2 shrink-0">
      <ThemeToggle />
    </div>
  </div>
</nav>

// src/components/nav-bar.tsx
"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { siteConfig } from "@/lib/config/site";
import { ThemeToggle } from "@/components/theme-toggle";

export function NavBar() {
  const pathname = usePathname();

  const isActive = (href: string) => {
    if (href === '/') return pathname === '/';
    return pathname.startsWith(href);
  };

  const crumbs = (() => {
    const path = pathname.replace(/\/$/, '') || '/';
    if (path === '/') return [];
    const parts = path.split('/').filter(Boolean);
    const displayNames: Record<string, string> = {
      posts: '文章',
      about: '关于',
      cover: '封面',
    };
    const result: { label: string; href: string }[] = [];
    let accumulated = '';
    for (const part of parts) {
      accumulated += '/' + part;
      result.push({ label: displayNames[part] || part, href: accumulated });
    }
    return result;
  })();

  return (
    <nav className="sticky top-0 z-40 w-full bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60 shadow-sm">
      <div className="flex h-12 items-center justify-between px-3">
        <div className="flex items-center gap-1 min-w-0 overflow-hidden">
          {/* Logo */}
          <Link href="/" className="shrink-0 hover:opacity-80 transition-opacity mr-1">
            <img
              src={siteConfig.avatar}
              alt="Home"
              className="h-6 w-6 rounded-full"
              referrerPolicy="no-referrer"
            />
          </Link>

          {/* Nav Links */}
          {siteConfig.navLinks.map((link) => (
            <Link
              key={link.href}
              href={link.href}
              className={`text-xs font-medium px-2 py-1 rounded-md transition-colors whitespace-nowrap shrink-0 ${
                isActive(link.href)
                  ? 'text-foreground bg-muted'
                  : 'text-muted-foreground hover:text-foreground hover:bg-muted/50'
              }`}
            >
              {link.label}
            </Link>
          ))}

          {/* Breadcrumbs - hidden on mobile when too long */}
          {crumbs.length > 0 && (
            <>
              <span className="text-muted-foreground/30 mx-0.5 shrink-0 hidden sm:inline">|</span>
              <div className="hidden sm:flex items-center gap-0.5 min-w-0 overflow-hidden">
                {crumbs.map((crumb, i) => (
                  <div key={crumb.href} className="inline-flex items-center gap-0.5 min-w-0">
                    <span className="text-muted-foreground/40 shrink-0">/</span>
                    {i < crumbs.length - 1 ? (
                      <Link href={crumb.href} className="text-xs text-muted-foreground hover:text-foreground truncate transition-colors shrink min-w-0 max-w-[80px]">
                        {crumb.label}
                      </Link>
                    ) : (
                      <span className="text-xs text-foreground font-medium truncate shrink min-w-0 max-w-[100px]">{crumb.label}</span>
                    )}
                  </div>
                ))}
              </div>
            </>
          )}
        </div>
        <div className="flex items-center gap-2 shrink-0">
          <ThemeToggle />
        </div>
      </div>
    </nav>
  );
}
