// src/lib/components/ThemeToggle.svelte
<script lang="ts">
  import { themeMode, isDark, type ThemeMode } from '$lib/stores/theme';
  import Icon from '@iconify/svelte';

  const modes: ThemeMode[] = ['light', 'dark', 'system'];

  function cycle() {
    themeMode.update((cur) => {
      const idx = modes.indexOf(cur);
      return modes[(idx + 1) % modes.length];
    });
  }

  const icon = $derived.by(() => {
    switch ($themeMode) {
      case 'light': return 'mdi:weather-sunny';
      case 'dark': return 'mdi:weather-night';
      case 'system': return 'mdi:monitor';
    }
  });

  const label = $derived.by(() => {
    switch ($themeMode) {
      case 'light': return '浅色模式';
      case 'dark': return '深色模式';
      case 'system': return '跟随系统';
    }
  });
</script>

<button
  onclick={cycle}
  class="inline-flex items-center justify-center rounded-md w-8 h-8 text-muted-foreground hover:bg-accent hover:text-accent-foreground transition-colors"
  aria-label={label}
  title={label}
>
  <Icon {icon} class="w-5 h-5" />
</button>

// src/components/theme-toggle.tsx
"use client";

import { useTheme } from "@/components/theme-provider";
import { Sun, Moon, Monitor } from "lucide-react";

const modes = ["light", "dark", "system"] as const;

export function ThemeToggle() {
  const { theme, setTheme } = useTheme();

  const cycle = () => {
    const idx = modes.indexOf(theme);
    setTheme(modes[(idx + 1) % modes.length]);
  };

  const Icon = theme === "light" ? Sun : theme === "dark" ? Moon : Monitor;
  const label = theme === "light" ? "浅色模式" : theme === "dark" ? "深色模式" : "跟随系统";

  return (
    <button
      onClick={cycle}
      className="inline-flex items-center justify-center rounded-md w-8 h-8 text-muted-foreground hover:bg-accent hover:text-accent-foreground transition-colors"
      aria-label={label}
      title={label}
    >
      <Icon className="w-5 h-5" />
    </button>
  );
}
